export default [
   {name: 'olma',       color: '#8DA35F'},
   {name: 'behi',       color: '#fdeb1c'},
   {name: 'shaftoli',   color: '#ba2222'},
   {name: 'qayragoch',  color: '#32452E'},
   {name: 'archa',      color: '#47BE60'},
   {name: 'gilos',      color: '#3E4AAD'},
   {name: 'nok',        color: '#CF9D46'},
   {name: 'tut',        color: '#EEEDED'},
   {name: "o'rik",        color: '#FFAFAF'},
   {name: "gujum",        color: '#6BD0FF'},
   {name: "sasna",        color: '#000000'},
   {name: "akatsiya",        color: '#fd0b1c'},
   {name: "yasin",        color: '#F3CE56'},
   {name: "jiyda",        color: '#A43481'},
]